default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: watila
  password: 

development:
  <<: *default
  database: novo_amigo_secreto_development

test:
  <<: *default
  database: novo_amigo_secreto_test

production:
  <<: *default
  database: novo_amigo_secreto_production
  username: novo_amigo_secreto
  password: <%= ENV['NOVO_AMIGO_SECRETO_DATABASE_PASSWORD'] %>
